# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        database_users:
            entity: { class: AppBundle:User, property: username}
#            entity:
#                class: AppBundle::User
#                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: security_profile
#                csrf_token_generator: security.csrf.token_manager
#                default_target_path: galery_index

#                csrf_parameter: _csrf_security_token
#                csrf_token_id: a_private_string

#                username_parameter: _username
#                password_parameter: _password
            logout:
                path: security_logout
#                target: homepage
                target: security_login

        main:
            anonymous: ~
            provider: database_users

#            form_login:
#                check_path: security_login
#                login_path: security_login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
#        - { path: ^/register, roles: ROLE_NO_ACCESS }
#        - { path: ^/login, roles: ROLE_NO_ACCESS }
        # require ROLE_ADMIN for /admin*
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/user, roles: ROLE_USER }